### ISSUE TITLE
I want to get whether the specified interfaceinfo.id is connected

### ISSUE THREAD

**Issue by dzx815** [emoacht/ManagedNativeWifi#21]
![image](https://user-images.githubusercontent.com/15151459/138245113-0c8fbc54-803e-427b-a71f-4788e686c79e.png)

function  NativeWifi.EnumerateInterfaceConnections().FirstOrDefault().IsConnected   can，But I feel that it does not necessarily correspond to the specified interfaceinfo. ID

**Comment by emoacht** [comment]
In fact, it is fairly easy.

```csharp
private static bool IsInterfaceConnected(Guid interfaceId)
{
    return NativeWifi.EnumerateInterfaceConnections()
        .FirstOrDefault(x => x.Id == interfaceId)
        is { IsConnected: true };
}
```
