### ISSUE TITLE
Duplicates returned by EnumerateAvailableNetworks() when profile exists

### ISSUE THREAD

**Issue by StevenWelsh** [emoacht/ManagedNativeWifi#23]
Same issue exists for EnumerateAvailableNetworkSsids()

SSIDs are duplicated in the returned data when a profile exists?

**Comment by emoacht** [comment]
I am not sure what you found but in general, what you found is what the OS returmed.
How to process the results is up to the app.

**Comment by hhgm** [comment]
Newer AP's emit th same SSID for both a 2.4 and a 5 G point. This could very likely be the source for 2 identical nodes.
