### ISSUE TITLE
Often find just one WiFi access point

### ISSUE THREAD

**Issue by LiQuick** [emoacht/ManagedNativeWifi#24]
Dear readers,

Any idea why I only find one WiFi access point when using NativeWifi.EnumerateBssNetworks(), although Windows shows like 9. And sometimes I get all 9. I am doing this 5 times and each time I also do the following:
               Task<IEnumerable<Guid>> task_Refresh = NativeWifi.ScanNetworksAsync(timeout: TimeSpan.FromSeconds(10));
                IEnumerable<Guid> guids = await task_Refresh;

Best regards and thx for your help,
Rémy Samulski

**Comment by emoacht** [comment]
I have no idea.
