### ISSUE TITLE
Query: is there any way to get information about bssid of currently connected network.

### ISSUE THREAD

**Issue by ravibajpai001** [emoacht/ManagedNativeWifi#31]
I checked there is one API, which gives SSID of currently connected network enumerateConnectedNetworkSsids. but I am looking for . BSSID, I can match sssid value with bss network but there can be multiple connections with the same SSID but different bssid.
Thanks

**Comment by ngocducdim** [comment]
As far as I know, we can get all BSSID connected of all network interface by using this command(`netsh wlan show interfaces
`) and query the string:
![image](https://github.com/emoacht/ManagedNativeWifi/assets/97713182/1b863e39-fa33-4665-9c0c-a8d27e34132b)
