### ISSUE TITLE
How do I connect?

### ISSUE THREAD

**Issue by NoteToSelfFindGoodNickname** [emoacht/ManagedNativeWifi#34]
No sample is given how to connect to a "new" network.

The required profile part is completely left out.

Why?

**Comment by emoacht** [comment]
You need to create a wireless profile before trying to connect to a wireless network.
The content of a profile is represented in XML and heavily dependent on each network. The building of a profile XML itself is out of scope of Native Wifi.

You can find profile XML's [schema](https://learn.microsoft.com/en-us/windows/win32/nativewifi/wlan-profileschema-elements) and [samples](https://learn.microsoft.com/en-us/windows/win32/nativewifi/wireless-profile-samples).
Perhaps you can create a simple sample profile relatively easily. However, creating profiles for practical usage and testing them  will be tough task.

Once you created a profile XML, you can add it by SetProfile method.
