### ISSUE TITLE
Get currently connected signal strength

### ISSUE THREAD

**Issue by notblam** [emoacht/ManagedNativeWifi#38]
I'm trying to find a way to get the currently connected network adapter and the signal strength that's used to make the wifi icon in the windows task bar.  Is there support for this?  

I doesn't seem like this is possible.  Maybe this could help implement this?
https://learn.microsoft.com/en-us/windows/win32/api/iphlpapi/nf-iphlpapi-getbestinterface

**Comment by emoacht** [comment]
You can get the link quality of currently connected wireless network by the combination of `EnumerateInterfaceConnections` and `EnumerateAvailableNetworkGroups`. Regarding the signal streanth, it has an issue on Windows 11. See #20

```csharp
var connectedInterfaceIds = NativeWifi.EnumerateInterfaceConnections()
    .Where(x => x.IsConnected)
    .Select(x => x.Id)
    .ToArray();

var connectedNetworkGroups = NativeWifi.EnumerateAvailableNetworkGroups()
    .Where(x => connectedInterfaceIds.Contains(x.Interface.Id))
    .ToArray();

foreach (var id in connectedNetworkGroups)
{
    Trace.WriteLine($"SSID: {id.Ssid} Linq quality: {id.LinkQuality}");
}
```

If you are talking about the case where a PC is connected to multiple wireless networks simultaneously and the way to tell which wireless connection information is shown in the system tray, I don't know how the OS does it.

I am not failiar to `GetBestInterface` function but I guess it has nothing to do with this case.
