### ISSUE TITLE
Add support for WlanRegisterNotification() Event handler

### ISSUE THREAD

**Issue by snandaworld** [emoacht/ManagedNativeWifi#39]
Should be able to handle below activities with by registering an event handler.

wlan_notification_acm_start,
  wlan_notification_acm_autoconf_enabled,
  wlan_notification_acm_autoconf_disabled,
  wlan_notification_acm_background_scan_enabled,
  wlan_notification_acm_background_scan_disabled,
  wlan_notification_acm_bss_type_change,
  wlan_notification_acm_power_setting_change,
  wlan_notification_acm_scan_complete,
  wlan_notification_acm_scan_fail,
  wlan_notification_acm_connection_start,
  wlan_notification_acm_connection_complete,
  wlan_notification_acm_connection_attempt_fail,
  wlan_notification_acm_filter_list_change,
  wlan_notification_acm_interface_arrival,
  wlan_notification_acm_interface_removal,
  wlan_notification_acm_profile_change,
  wlan_notification_acm_profile_name_change,
  wlan_notification_acm_profiles_exhausted,
  wlan_notification_acm_network_not_available,
  wlan_notification_acm_network_available,
  wlan_notification_acm_disconnecting,
  wlan_notification_acm_disconnected,
  wlan_notification_acm_adhoc_network_state_change,
  wlan_notification_acm_profile_unblocked,
  wlan_notification_acm_screen_power_change,
  wlan_notification_acm_profile_blocked,
  wlan_notification_acm_scan_list_refresh,
  wlan_notification_acm_operational_state_change,
  wlan_notification_acm_end

**Comment by emoacht** [comment]
You can use `NativeWifiPlayer` class

**Comment by snandaworld** [comment]
Could you please give an example to implement Profile changed event handler??
