### ISSUE TITLE
Initializing nativewifiplayer class will register for WLAN notifications even though not registered from initialized variable.

### ISSUE THREAD

**Issue by snandaworld** [emoacht/ManagedNativeWifi#43]
Initializing nativewifiplayer class will register for WLAN notifications even though not registered from initialized variable.

This will cause the app to crash when nativewifiplayer and NativeWiFi both the class are used.

It's better to have all the methods and functiones under one class.

it should register for notifications only when it is intended.

**Comment by emoacht** [comment]
DONT use NativeWifi's static methods and NativeWifiPlayer's instance method at the same time.
