### ISSUE TITLE
Please add the option to retrieve a Profile's stored password

### ISSUE THREAD

**Issue by Steffens-Bridgemate** [emoacht/ManagedNativeWifi#44]
I can retrieve the stored profiles all right, but not their stored passwords. That would be really helpful.

**Comment by emoacht** [comment]
There is no password in a wireless profile. Anyway, sensitive information is encrypted by the OS.

**Comment by Steffens-Bridgemate** [comment]
I beg to differ: could you have a look at this post? The author is able to retrieve the wireless profile password using the Native Wifi Api

**Comment by emoacht** [comment]
I see. This person calls KeyMaterial as "password".
It is usually included in ProfileDocument.Xml. It is encrypted though.
