### ISSUE TITLE
DeleteProfile method is throwing error

### ISSUE THREAD

**Issue by ovpoddar** [emoacht/ManagedNativeWifi#45]
so here is my small setup of using DeleteProfile method.

```
var targetProfile = NativeWifi.EnumerateProfiles()
		.FirstOrDefault();

if (targetProfile == null)
	return;

NativeWifi.DeleteProfile(
	interfaceId: targetProfile.Interface.Id,
	profileName: targetProfile.Name);
```

I guess it looks totally reasonable. but it throwing this error
### **System.ComponentModel.Win32Exception: 'MethodName: WlanDeleteProfile, ErrorCode: 2, ErrorMessage: The system cannot find the file specified.**

I checked my C:\ProgramData\Microsoft\Wlansvc\Profiles\Interfaces\'{my interface id}' folder and confirm that the profile does exist. So why its throwing the exception?

**Comment by emoacht** [comment]
I don't know why but could you try NativeWifiTest in ManagedNativeWifi.Test?

**Comment by emoacht** [comment]
I don't know how your system was weird at that moment. You should have checked interface id and profile name before calling DeleteProfile. My guess is the returned value from WlanGetProfileList was weird.

**Comment by ovpoddar** [comment]
Thanks for the response. I will keep that in mind.
