### ISSUE TITLE
Unhandled System.Reflection.TargetInvocationException when WLANSVC is not running

### ISSUE THREAD

**Issue by kellybs1** [emoacht/ManagedNativeWifi#47]
Test OS: Windows 10.0.19045
ManagedNativeWifi version: 2.5.0.0.
IDE/ENV: Microsoft Visual Studio Enterprise 2019 Version 16.11.17

Noted this issue testing software on Virtual Machines with no Wifi capabilities that by default do not run the WLANSVC service.
Worked-around by try-catching the exception.

Note this is only confirmed using the EnumerateInterfaces() method. I suspect it will occur elsewhere ( WlanOpenHandle calls ).
This occurs with ThrowsOnAnyFailure set to false.

Steps to reproduce:
- Open a admin-level PowerShell and stop the WLANSVC service with the command "net stop wlansvc"

- Call the NativeWifi.EnumerateInterfaces() method, eg:

```
public static void ThrowException()
{
    NativeWifi.ThrowsOnAnyFailure = false;

    try
    {
        var wifiInterfaces = NativeWifi.EnumerateInterfaces();
    }
    catch ( Exception e )
    {
        Debug.WriteLine( e.InnerException?.Message );
        int putABreakPointHere = 0;
    }
}    
```

- Note the error:
> Exception thrown: 'System.Reflection.TargetInvocationException' in mscorlib.dll
> MethodName: WlanOpenHandle, ErrorCode: 1062, ErrorMessage: The service has not been started.

( Don't forget to "net start wlansvc" again or your Wifi won't work ;) )

**Comment by emoacht** [comment]
Thank you for reporting.
It is obvious that if the service is stopped, that exception will be thrown.
In case where such thing is expected, we can check if theservice is running before calling this library.

```csharp
var controller = new System.ServiceProcess.ServiceController("WLANSVC");
if (controller.Status is not ServiceControllerStatus.Running)
{
    return; // exit
}
```
