### ISSUE TITLE
Can't connect to wifi when using Ethernet

### ISSUE THREAD

**Issue by granduros** [emoacht/ManagedNativeWifi#48]
Im trying to connect to a specific wifi but i can't connect when im already connected to a Ethernet connection. When running the ConnectNetwork it responds with true but the network is not connected.

**Comment by emoacht** [comment]
It depends on the WiFi access point. I can connect to mine both by Ethernet and by WiFi at the same time.

**Comment by granduros** [comment]
Can you elaborate? It works fine when going from one wifi to another.

**Comment by emoacht** [comment]
Ask your access point's vender.

**Comment by granduros** [comment]
The issue was caused by the network group policy, no issues were found using ethernet on a network with another policy
