### ISSUE TITLE
Connecting to a network with temporary profile

### ISSUE THREAD

**Issue by Menelion** [emoacht/ManagedNativeWifi#50]
I would like to develop an alternative simplified UI to Windows wireless settings. This would require the user to select an available network and then connect to it.  
The underlying Native WiFi API has a [wlan_connection_mode](https://learn.microsoft.com/en-us/windows/win32/api/wlanapi/ne-wlanapi-wlan_connection_mode) enum which can allow connecting with a temporary profile created on the fly.  
In this library however the connection mode is always set to `profile`. Aren't you considering adding this functionality? Thanks.

**Comment by emoacht** [comment]
No plan to add that functionality.
