### ISSUE TITLE
Sometimes could only get one WIFI network

### ISSUE THREAD

**Issue by jarodxiangliu** [emoacht/ManagedNativeWifi#53]
There are lots of nearby WIFI networks available, but sometimes call **NativeWifi.EnumerateAvailableNetworks()** could only get one network return. Click the wifi icon of system seems could fix this issue.

**Comment by emoacht** [comment]
In such case, call ScanNetworksAsync and the call EnumerateAvailableNetworks again.

**Comment by jarodxiangliu** [comment]
Thanks for your quick support!
About calling  ScanNetworksAsync, it need to set a timeout. Which value will be better? Could you help providing suggestion?
Thanks again in advance!

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: emoacht ***@***.***>
发送时间: Tuesday, January 23, 2024 4:06:34 PM
收件人: emoacht/ManagedNativeWifi ***@***.***>
抄送: jarodxiangliu ***@***.***>; Author ***@***.***>
主题: Re: [emoacht/ManagedNativeWifi] Sometimes could only get one WIFI network (Issue #53)


In such case, call ScanNetworksAsync and the call EnumerateAvailableNetworks again.

―

**Comment by emoacht** [comment]
Perhaps this could help you.

> Wireless network drivers that meet Windows logo requirements are required to complete a WlanScan function request in 4 seconds.

https://learn.microsoft.com/en-us/windows/win32/api/wlanapi/nf-wlanapi-wlanscan

**Comment by jarodxiangliu** [comment]
Thanks very much for your quick reply. Great help, very appreciate!

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: emoacht ***@***.***>
发送时间: Tuesday, January 23, 2024 6:31:19 PM
收件人: emoacht/ManagedNativeWifi ***@***.***>
抄送: jarodxiangliu ***@***.***>; Author ***@***.***>
主题: Re: [emoacht/ManagedNativeWifi] Sometimes could only get one WIFI network (Issue #53)


Perhaps this could help you.

Wireless network drivers that meet Windows logo requirements are required to complete a WlanScan function request in 4 seconds.

https://learn.microsoft.com/en-us/windows/win32/api/wlanapi/nf-wlanapi-wlanscan

―

**Comment by jarodxiangliu** [comment]
Run ScanNetworksAsync and then call EnumerateAvailableNetworks could exactly solve this issue. But seems ScanNetworksAsync will cost seconds time. for performance, Are there any condition could help to decide whether need to run ScanNetworksAsync?
I mean
var availableNetworks = NativeWifi.EnumerateAvailableNetworks();
**if (condition)**
{
       NativeWifi.ScanNetworksAsync(new TimeSpan(0, 0, 0, 4)).GetAwaiter().GetResult();
       availableNetworks = NativeWifi.EnumerateAvailableNetworks();
}
Now I am checking the count of networks returned from last call, in my machine, it worked. But I am not sure whether there are better checking condition for this case.

**Comment by emoacht** [comment]
No. AFAIK, there are no means of the getting the latest Wi-Fi networks' states without rescan.
How to mitigate the impact is up to the caller.

**Comment by jarodxiangliu** [comment]
Got it! Thanks for your confirmation!

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: emoacht ***@***.***>
发送时间: Thursday, January 25, 2024 3:38:29 PM
收件人: emoacht/ManagedNativeWifi ***@***.***>
抄送: jarodxiangliu ***@***.***>; Author ***@***.***>
主题: Re: [emoacht/ManagedNativeWifi] Sometimes could only get one WIFI network (Issue #53)


No. AFAIK, there are no means of the getting the latest Wi-Fi networks' states without rescan.
How to mitigate the impact is up to the caller.

―
