### ISSUE TITLE
Are there any events that you can listen/subscribe to?

### ISSUE THREAD

**Issue by mhemy** [emoacht/ManagedNativeWifi#56]
I did not see any events you can subscribe to, for example when a scan completed, or a profile changed, or a wifi network got connected or disconnected. Do they exist and are just not documented?

**Comment by emoacht** [comment]
See NativeWifiPlayer class.
https://github.com/emoacht/ManagedNativeWifi/blob/master/Source/ManagedNativeWifi/NativeWifiPlayer.cs
