### ISSUE TITLE
Connection Question

### ISSUE THREAD

**Issue by MaroisConsulting** [emoacht/ManagedNativeWifi#58]
This class is great. Thanks for the hard work.

I can use this class to get a list of WIFI networks, but from what I can see, the class only provides for connections to network via a profile.

I have about 15 different WIFI networks in my area.  When I try to connect, I get prompted for passwords.  I need to be able to connect to any of them via password.  I don't have profiles for them. Can I do this?

Thanks

**Comment by emoacht** [comment]
You need to have a profile first. It is how Native Wifi API works.
