### ISSUE TITLE
Usage.SetProfile(..)

### ISSUE THREAD

**Issue by arham-anees** [emoacht/ManagedNativeWifi#7]
i am trying to set profile but it is giving error codes of 87,1338 etc.. i copied xml text from deleteProfile function that has been stored in system and tried to save again after deleting but still giving issue.
after research on error code 1338 i found that [The security descriptor structure is invalid](https://support.microsoft.com/en-us/help/2459083/robocopy-may-report-error-1338-the-security-descriptor-structure-is-in). i dont know what security should be provided in form of string as documentation also donot mention any thing regarding this..

**Comment by emoacht** [comment]
Hi,
`DeleteProfile` method doesn't produce a profile XML string.
Anyways, for security descriptor when using `SetProfile` method, I think you should refer to Remarks of  [WlanSetProfile](https://docs.microsoft.com/en-us/windows/desktop/api/wlanapi/nf-wlanapi-wlansetprofile#remarks) function. In general, setting a profile is somewhat onerous and painful.
